### PR TITLE
image is more responsive and css move to separate file

### PR DESCRIPTION
**Pull request by Dhairyash-1**
I have make image more responsive on mobile device and moved css from html file to style.css so code look much clear

### CODE REVIEW

**Comment by Dhairyash-1** [comment]
I have made the image more responsive on a mobile device and moved CSS from an HTML file to style.css so the code looks much clear

**Comment by Tejas-Dalvi-99** [comment]
Can you please attach the screenshots of the New changes of CSS. Is it working perfectly Fine ?

**Comment by Dhairyash-1** [comment]
Screenshot (20)
Screenshot (21)
Screenshot (23)
@Tejas-Dalvi-99  You can see here now images are more responsive on mobile.

**Comment by Dhairyash-1** [comment]
and it is working completely fine.

**Pull request merged**
