### PR TITLE
initial commit

### LINKED ISSUE #16: Improve UI of Navigation bar
@Tejas-Dalvi-99 , Please assign this task to me with Hacktoberfest label.
Is this repo is taking part in Hacktoberfest2022?

### PR DESCRIPTION
**Pull request by MadhuSaini22**
this issue resolves #16

### CODE REVIEW

**Comment by Tejas-Dalvi-99** [comment]
What changes have Been made ?

**Comment by MadhuSaini22** [comment]
> What changes have Been made ?
changed from this  : 

to this :

**Comment by MadhuSaini22** [comment]
@Tejas-Dalvi-99 , you can merge now :)

**Comment by MadhuSaini22** [comment]
last commit resolves #27 
 changed this:
image
 from this:
image

**Comment by MadhuSaini22** [comment]
@Tejas-Dalvi-99 , please merge now :)

**Review by Tejas-Dalvi-99 — APPROVED** [review]

**Review by Tejas-Dalvi-99 — COMMENTED** [review]
Actually we need the emergency button to Be a bit Bigger and Circular

**Comment by MadhuSaini22** [comment]
> Actually we need the emergency button to Be a bit Bigger and Circular

In the Home page as well, according to your need
Changed this:

from this:

**Comment by Tejas-Dalvi-99** [comment]
https://www.behance.net/gallery/105647943/Callert-life-saving-procedures-digitized

Can you check this Link out, We need the button to look something like this

**Comment by MadhuSaini22** [comment]
> https://www.behance.net/gallery/105647943/Callert-life-saving-procedures-digitized
> 
> Can you check this Link out, We need the button to look something like this

Can u please share screenshot of what kind of button you want, so it will be clear to me

**Comment by MadhuSaini22** [comment]
> https://www.behance.net/gallery/105647943/Callert-life-saving-procedures-digitized
> 
> Can you check this Link out, We need the button to look something like this

okay I got it

**Comment by MadhuSaini22** [comment]
@Tejas-Dalvi-99 is this okay now?

image


on hover:
image

**Comment by Tejas-Dalvi-99** [comment]
Yup That is Exactly what we needed Great Efforts!

**Pull request merged**
