### PR TITLE
Fixed the Invalid HTMLs.

### LINKED ISSUE #14: Fixed the Invalid HTMLs.
There are a lot of invalid HTMLs. We need to fix them. I am on it.

### PR DESCRIPTION
**Pull request by praveenscience**
Changes done:

* Removed most of the dubious inline styles.
* Created an embedded stylesheet.
* Removed unclosed and pre-closed invalid tags.
* Checked with the right HTML Standards.

ToDo: Fix all the rows and cols in Bootstrap way.

Fixes #14.

### CODE REVIEW

**Comment by Tejas-Dalvi-99** [comment]
Did you test The code ?

**Comment by praveenscience** [comment]
Yes, I tested it and it works perfectly. At least better than what was there before.

**Comment by Tejas-Dalvi-99** [comment]
Done !

**Comment by praveenscience** [comment]
@Tejas-Dalvi-99 Here's a screenshot if you like:

image

**Comment by praveenscience** [comment]
@Tejas-Dalvi-99 Here's a screenshot if you like:

image

**Pull request merged**
