### PR TITLE
Emergency Form Modification and added CSS to it

### PR DESCRIPTION
**Pull request by nik-agarwal12**
Hey Coder @Tejas-Dalvi-99 , kindly review my PR. I have made the following changes :- 
1. Modified Emergency Form to add some more fields.
2. Added lots of CSS to make the page beautiful.

### CODE REVIEW

**Comment by Tejas-Dalvi-99** [comment]
We have decided to keep it simple and Classic, Could you please make a Simple UI ( CSS ) for the form . and we don't need the dark theme

**Comment by nik-agarwal12** [comment]
Okay I will do the same and PR again.
Thanks & Regards.

**Comment by Tejas-Dalvi-99** [comment]
Hey @nik-agarwal12 The Contributers Codes Folder have been Removed, So just Change the path of Emergency form.html by removing the Contributers Codes in the path in file Name and make The PR . The path should look like this :-  Help-Me / Emergency Form.html .

**Comment by Tejas-Dalvi-99** [comment]
image

Still it is having conflicts with Main Branch please check

**Comment by nik-agarwal12** [comment]
Okay I will look into it

**Pull request closed without merging**
